### ISSUE TITLE
Why is the NPU simulator code missing in the execution engine module? How can we add our own simulator? 

### ISSUE THREAD

**Issue by tjseek** [casys-kaist/LLMServingSim#2]
![image](https://github.com/user-attachments/assets/9ac4eb32-070f-47cb-a2c7-b304d502db3a)
I think this part of the code is missing, but I'm not sure where to add it.
And I run simulate.py,  the simulation result is empty. like that 
![image](https://github.com/user-attachments/assets/8c22e5b9-98b3-433b-b86f-f0944237070b)

**Comment by JaehongCS20** [comment]
We used an internal simulator called 'GeneSys,' but since it is difficult to make it publicly available, we have not released it. You can find more information about ‘GeneSys’ at the following link:[ https://actlab-genesys.github.io/](https://actlab-genesys.github.io/)

However, a previous version of the simulator is available, and you can use it to run the execution engine effectively. The link to the older version is provided below:[ https://github.com/VeriGOOD-ML/public](https://github.com/VeriGOOD-ML/public)

LLMServingSim compiles NPUs using codelets and Polymath, just like in the code above, so there should be no issues with integration. Furthermore, you don’t necessarily have to use this specific NPU simulator; you can integrate a completely new compiler and simulator. Since we compile and simulate the model by splitting it into ONNX models, you may want to explore other simulators that accept ONNX models as input.

**Comment by tjseek** [comment]
Thank you very much for your detailed reply! 

1. In the code repository VeriGOOD provided by you, I find that the simDIT module simulates the cycle and access indicators of some operators. However, there are only several operators, such as conv/GEMM of the Systolic type，ReLU/ElemAdd/MaxPool/Softmax of the SIMD type. Many other operator simulation models in LLMservingSim are missing. 
2. In addition, I found that the simulation interfaces of these operators have many hardware configuration parameters, which are complex and difficult to understand. According to my understanding, LLMservingSim simulates the operators at each layer in each block to obtain the final cycles and access data. So can you provide the simulation code of the missing operators in LLMservingSim?

**Comment by tjseek** [comment]
below is our excution engine  output results

ORCA		model_parallel_NPU_group: 1
1355
Layername                        comp_time     input_loc   input_size  weight_loc  weight_size output_loc  output_size comm_type   comm_size   misc        
elem_gather1_0                   28230         LOCAL       2           REMOTE      411705344   REMOTE      16384       NONE        0           NONE        
elem_add3d3d2_1                  6374          LOCAL       16384       REMOTE      0           REMOTE      8192        NONE        0           NONE        
reduce_mean3d1_2                 4951          LOCAL       8192        REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_sub3d3d2_3                  374           LOCAL       8194        REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_pow3d3_4                    295           LOCAL       8194        REMOTE      0           REMOTE      8192        NONE        0           NONE        
reduce_mean3d4_5                 4951          LOCAL       8192        REMOTE      0           REMOTE      4           NONE        0           NONE        
elem_add3d_const5_6              294           LOCAL       4           REMOTE      0           REMOTE      2           NONE        0           NONE        
elem_sqrt3d6_7                   306           LOCAL       2           REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_div3d3d7_8                  642           LOCAL       8194        REMOTE      0           REMOTE      8192        NONE        0           NONE        
elem_mul3d1d8_9                  6114          LOCAL       8192        REMOTE      8192        REMOTE      8192        NONE        0           NONE        
elem_add3d1d9_10                 6114          LOCAL       8192        REMOTE      8192        REMOTE      8192        NONE        0           NONE        
gemm1_11                         5148          LOCAL       8192        REMOTE      100687872   REMOTE      24576       NONE        0           NONE        
ATTENTION 0                                                                                                                                                
tensor_transpose4d1_13           1110          LOCAL       8192        REMOTE      0           REMOTE      8192        NONE        0           NONE        
tensor_transpose4d2_14           1110          LOCAL       8192        REMOTE      0           REMOTE      8192        NONE        0           NONE        
tensor_transpose4d3_15           1110          LOCAL       8192        REMOTE      0           REMOTE      122880      NONE        0           NONE        
matmul4d6_16                     863           LOCAL       122880      REMOTE      0           REMOTE      898         NONE        0           NONE        
elem_div_const7_17               577           LOCAL       898         REMOTE      0           REMOTE      896         NONE        0           NONE        
softmax4d8_18                    1057          LOCAL       896         REMOTE      0           REMOTE      115584      NONE        0           NONE        
matmul4d9_19                     863           LOCAL       115584      REMOTE      0           REMOTE      8192        NONE        0           NONE        
tensor_transpose4d10_20          309           LOCAL       8192        REMOTE      0           REMOTE      8192        NONE        0           NONE        
ATTENTION END                                                                                                                                              
gemm1_22                         2261          LOCAL       8192        REMOTE      33562624    REMOTE      16384       ALLREDUCE   16384       NONE        
elem_add3d3d3_23                 6374          LOCAL       16384       REMOTE      0           REMOTE      8192        NONE        0           NONE        
reduce_mean3d1_24                4951          LOCAL       8192        REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_sub3d3d2_25                 374           LOCAL       8194        REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_pow3d3_26                   295           LOCAL       8194        REMOTE      0           REMOTE      8192        NONE        0           NONE        
reduce_mean3d4_27                4951          LOCAL       8192        REMOTE      0           REMOTE      4           NONE        0           NONE        
elem_add3d_const5_28             294           LOCAL       4           REMOTE      0           REMOTE      2           NONE        0           NONE        
elem_sqrt3d6_29                  306           LOCAL       2           REMOTE      0           REMOTE      8194        NONE        0           NONE        
elem_div3d3d7_30                 642           LOCAL       8194        REMOTE      0           REMOTE      8192        NONE        0           NONE        
elem_mul3d1d8_31                 6114          LOCAL       8192        REMOTE      8192        REMOTE      8192        NONE        0           NONE        
elem_add3d1d9_32                 6114          LOCAL       8192        REMOTE      8192        REMOTE      8192        NONE        0           NONE        
gemm1_33                         6592          LOCAL       8192        REMOTE      134250496   REMOTE      32770       NONE        0           NONE        
elem_mul3d_const3_34             23169         LOCAL       32770       REMOTE      0           REMOTE      32770       NONE        0           NONE        
elem_pow3d4_35                   296           LOCAL       32770       REMOTE      0           REMOTE      32770       NONE        0           NONE        
elem_mul3d_const5_36             23169         LOCAL       32770       REMOTE      0           REMOTE      65536       NONE        0           NONE        
elem_add3d3d6_37                 25497         LOCAL       65536       REMOTE      0           REMOTE      32770       NONE        0           NONE        
elem_mul3d_const7_38             23169         LOCAL       32770       REMOTE      0           REMOTE      32768       NONE        0           NONE        
elem_tanh3d8_39                  20873         LOCAL       32768       REMOTE      0           REMOTE      32770       NONE        0           NONE        
elem_add3d_const9_40             23169         LOCAL       32770       REMOTE      0           REMOTE      65536       NONE        0           NONE        
elem_mul3d3d10_41                25497         LOCAL       65536       REMOTE      0           REMOTE      32768       NONE        0           NONE        
gemm1_42

**Comment by JaehongCS20** [comment]
## Answer
1. It seems that some operations are missing due to the use of an older simulator. I am aware of this issue, as I also experienced the same problem before the simulator was updated. To overcome it, I have used additional simulators. For example, I have tried using [SCALE-Sim](https://github.com/scalesim-project/scale-sim-v2) for the GEMM operation.

2. As for the configuration, you just need to match the NPU config in the codelet with the NPU config in the simulator. As I mentioned earlier in 1., I don’t have the authority to share the NPU simulator, as I’m also a user who has received access to it. I am also working on an alternative solution that you can use but I cannot guarantee how long this will take. Therefore, I would recommend understanding the code and changing the execution engine itself to better suit your research. There are many NPU simulators like [ONNXim](https://github.com/PSAL-POSTECH/ONNXim) in public.

## Tips For Changing the Execution Engine

As a small tip, the layers in the simulation trace (.txt) don’t necessarily have to match the exact layers in the model. The current layers (operations) in the trace are just an example of how the execution engine (compiler -> simulator pair) has analyzed the ONNX model. For instance, in the current trace generated by the execution engine (codelet -> GeneSys), the operations are broken down into smaller steps like layer_norm, elem_add, gemm, etc. However, it wouldn’t be an issue if you grouped them into larger layers such as QKV Gen, Attention, FFN1, and so on. 

One thing to note, though, is that when creating the trace, specific layers need to include ALL-REDUCE for parallelism, and for attention layers, each request should be simulated separately in hardware and labeled as "ATTENTION #" to fit the iteration-level scheduling of Orca. You can refer to the trace from `astra-sim/inputs/custom_workload` after running some evaluation script for further guidance on this.

## If You Want to Really Use SimDIT
I can provide an example piece of code using SimDIT and ScaleSim from the past. However, since this code is deprecated, it will be up to you to make it work properly. Additionally, certain smaller computations that are not supported can be ignored, as they are not dominant layers.
```python
from modified_SimDIT.main_simulator_module import SimDIT
from scalesim.scale_sim import scalesim

# use SimDIT
smdt = SimDIT()
directory = path.split('/')[0] + '/' + path.split('/')[1] + '/' + path.split('/')[2] + '/' + path.split('/')[3]+ '/' + path.split('/')[4]
json_name = path.split('/')[5]
batch = 1
comp_time = int(smdt.run(directory, json_name, batch))
# PREVENT OUT OF MEMORY
del smdt

# use ScaleSim
# make topology file
content_path = "scale-sim-v2"
config = content_path + "/configs/scale.cfg"
topo = content_path + "/topologies/gemm.csv"
    
if "gemm" in layer:
  B = 1
  C = 1
  M = TS.gemm[gemm_cnt][0][0]
  N = TS.gemm[gemm_cnt][0][1]
  K = TS.gemm[gemm_cnt][3][1]
  gemm_cnt += 1
  print(f"gemm: M: {M}, N: {N}, K: {K}")

elif "matmul" in layer:
  B = TS.matmul[matmul_cnt][0][0]
  C = TS.matmul[matmul_cnt][0][1]
  M = TS.matmul[matmul_cnt][0][2]
  N = TS.matmul[matmul_cnt][0][3]
  K = TS.matmul[matmul_cnt][2][3]
  matmul_cnt += 1
  print(f"matmul: B: {B}, C: {C}, M: {M}, N: {N}, K: {K}")

with open(topo,'w', newline='') as t:
  wr = csv.writer(t)
  wr.writerow(['Layer','M','N','K'])
  wr.writerow([1, M, N, K])

s = scalesim(save_disk_space=True, verbose=True,
    config=config,
    topology=topo,
    input_type_gemm=True)
  log = content_path + "/log"
  s.run_scale(top_path=log)

with open(log+"/GEMM/COMPUTE_REPORT.csv",'r', newline='') as l:
  rd = csv.reader(l)
  next(rd) # skip header
  for row in rd:
  comp_time = (int(row[1]) + int(row[2])) * B * C
  # PREVENT OUT OF MEMORY
  del s
```
